import { Router } from 'express';
import collegeRoutes from '../modules/colleges/routes/collegeRoutes.js';
import courseRoutes from '../modules/courses/routes/courseRoutes.js';
import examRoutes from '../modules/exams/routes/examRoutes.js';
import scholarshipRoutes from '../modules/scholorship/routes/scholorshipRoutes.js';
import recruitersRoutes from '../modules/recruiters/routes/recruitersRoutes.js';
import jobRoutes from '../modules/jobs/routes/jobRoutes.js';
import reviewRoutes from '../modules/reviews/routes/reviewRoutes.js';
import streamRoutes from '../modules/streams/routes/streamRoutes.js';
import universityRoutes from '../modules/universities/routes/universityRoutes.js';
import homePageCMSRoutes from '../modules/contentManagement/Homepage/routes/homePageCMSRoutes.js';
import blogCMSRoutes from '../modules/contentManagement/Blogpage/routes/blogCMSRoutes.js';
import aboutCMSRoutes from '../modules/contentManagement/Aboutpage/routes/aboutCMSRoutes.js';
import careerCMSRoutes from '../modules/contentManagement/Careerpage/routes/careerCMSRoutes.js';
import footerCMSRoutes from '../modules/contentManagement/Footer/routes/footerCMSRoutes.js';
import jobsInternshipsCMSRoutes from '../modules/contentManagement/JobsInternshipsPage/routes/jobsInternshipsCMSRoutes.js';
import examCMSRoutes from '../modules/contentManagement/ExamPage/routes/examCMSRoutes.js';
import coursesCMSRoutes from '../modules/contentManagement/CoursesPage/routes/coursesCMSRoutes.js';
import collegesCMSRoutes from '../modules/contentManagement/CollegesPage/routes/collegesCMSRoutes.js';
import searchRoutes from '../modules/search/routes/searchRoutes.js';
import blogRoutes from '../modules/blogs/routes/blogRoutes.js';
import userRoutes from '../modules/users/routes/userRoutes.js';

const router = Router();

router.use('/college', collegeRoutes);
router.use('/course', courseRoutes);
router.use('/exam', examRoutes);
router.use('/scholarship', scholarshipRoutes);
router.use('/recruiter', recruitersRoutes);
router.use('/job', jobRoutes);
router.use('/review', reviewRoutes);
router.use('/stream', streamRoutes);
router.use('/university', universityRoutes);
router.use('/reviews', reviewRoutes);
router.use('/search', searchRoutes);
router.use('/cms/homepage', homePageCMSRoutes);
router.use('/cms/blogpage', blogCMSRoutes);
router.use('/cms/aboutpage', aboutCMSRoutes);
router.use('/cms/careerpage', careerCMSRoutes);
router.use('/cms/footer', footerCMSRoutes);
router.use('/cms/jobsinternshipspage', jobsInternshipsCMSRoutes);
router.use('/cms/exampage', examCMSRoutes);
router.use('/cms/coursespage', coursesCMSRoutes);
router.use('/cms/collegespage', collegesCMSRoutes);
router.use('/blog', blogRoutes);
router.use('/users', userRoutes);

export default router;
