import { ExamData } from "../app/(routes)/exams/types/type";
import { ScholarshipData } from "../app/(routes)/scholarships/types/type";
import { JobData } from "../app/(routes)/jobs/types/type";



export const collegesDummyData = [
  {
    id: "1",
    name: "Indian Institute of Technology, Delhi",
    location: "Mumbai, Maharashtra",
    type: "Government",
    status: "Live",
    courses: 45,
    students: 12000,
    rating: 4.8,
    image: "/assets/DummyCollege.png",
  },
  {
    id: "2",
    name: "National Institute of Technology, Trichy",
    location: "Tiruchirappalli, Tamil Nadu",
    type: "Government",
    status: "Under Review",
    courses: 40,
    students: 6000,
    rating: 4.6,
    image: "/assets/DummyCollege.png",
  },
  {
    id: "3",
    name: "Indian Institute of Science, Bangalore",
    location: "Bangalore, Karnataka",
    type: "Government",
    status: "Live",
    courses: 50,
    students: 8500,
    rating: 4.7,
    image: "/assets/DummyCollege.png",
  },
  {
    id: "4",
    name: "Birla Institute of Technology and Science, Pilani",
    location: "Pilani, Rajasthan",
    type: "Private",
    status: "Draft",
    courses: 30,
    students: 10000,
    rating: 4.5,
    image: "/assets/DummyCollege.png",
  },
  {
    id: "5",
    name: "Vellore Institute of Technology, Vellore",
    location: "Vellore, Tamil Nadu",
    type: "Private",
    status: "Under Review",
    courses: 35,
    students: 14000,
    rating: 4.4,
    image: "/assets/DummyCollege.png",
  },
  {
    id: "6",
    name: "Manipal Academy of Higher Education, Manipal",
    location: "Manipal, Karnataka",
    type: "Private",
    status: "Draft",
    courses: 25,
    students: 9500,
    rating: 4.3,
    image: "/assets/DummyCollege.png",
  },
  {
    id: "7",
    name: "Indian Institute of Technology, Bombay",
    location: "Mumbai, Maharashtra",
    type: "Government",
    status: "Live",
    courses: 45,
    students: 11000,
    rating: 4.8,
    image: "/assets/DummyCollege.png",
  },
];


export const dummyExamTableData: ExamData[] = [
  {
    id: "1",
    name: "JEE Main",
    description: "Joint Entrance Examination",
    type: "Engineering",
    conductedBy: "NTA",
    frequency: "Twice a year",
    nextDate: "2024-03-31",
    registered: "1,250",
    status: "Active",
  },
  {
    id: "2",
    name: "JEE Advanced",
    description: "Joint Entrance Examination Advanced",
    type: "Engineering",
    conductedBy: "NTA",
    frequency: "Once a year",
    nextDate: "2024-05-26",
    registered: "2,500",
    status: "Closed",
  },
  {
    id: "3",
    name: "NEET",
    description: "National Eligibility cum Entrance Test",
    type: "Medical",
    conductedBy: "NTA",
    frequency: "Once a year",
    nextDate: "2024-05-05",
    registered: "1,600",
    status: "Active",
  },
  {
    id: "4",
    name: "CLAT",
    description: "Common Law Admission Test",
    type: "Law",
    conductedBy: "NLU",
    frequency: "Once a year",
    nextDate: "2024-12-01",
    registered: "1,200",
    status: "Upcoming",
  },
  {
    id: "5",
    name: "CAT",
    description: "Common Admission Test",
    type: "Management",
    conductedBy: "IIM",
    frequency: "Once a year",
    nextDate: "2024-11-24",
    registered: "2,000",
    status: "Active",
  },
  {
    id: "6",
    name: "GRE",
    description: "Graduate Record Examination",
    type: "Postgraduate",
    conductedBy: "ETS",
    frequency: "Year-round",
    nextDate: "2024-10-15",
    registered: "205",
    status: "Upcoming",
  },
  {
    id: "7",
    name: "GMAT",
    description: "Graduate Management Admission Test",
    type: "Management",
    conductedBy: "GMAC",
    frequency: "Year-round",
    nextDate: "2024-09-10",
    registered: "250",
    status: "Active",
  },
  {
    id: "8",
    name: "SAT",
    description: "Scholastic Assessment Test",
    type: "Undergraduate",
    conductedBy: "College Board",
    frequency: "Five times a year",
    nextDate: "2024-08-03",
    registered: "49",
    status: "Closed",
  },
];


export const dummyscholarshipData: ScholarshipData[] = [
  {
    id: "1",
    name: "National Merit Scholarship",
    subTitle: "Minimum 85% in 12th • UG",
    type: "Merit-Based",
    provider: "Government of India",
    amount: "₹50,000",
    deadline: "2024-03-31",
    applicants: "1,250",
    status: "Active",
  },
  {
    id: "2",
    name: "Fulbright Program",
    subTitle: "Bachelor's Degree • PG",
    type: "Merit-Based",
    provider: "U.S. Department of State",
    amount: "Varies",
    deadline: "2024-04-15",
    applicants: "2,000",
    status: "Active",
  },
  {
    id: "3",
    name: "Rhodes Scholarship",
    subTitle: "Undergraduate Degree • PG",
    type: "Merit-Based",
    provider: "University of Oxford",
    amount: "Full tuition",
    deadline: "2024-12-01",
    applicants: "100",
    status: "Active",
  },
  {
    id: "4",
    name: "Gates Cambridge Scholarship",
    subTitle: "Good Academic Record • PG",
    type: "Merit-Based",
    provider: "University of Cambridge",
    amount: "Full funding",
    deadline: "2024-01-05",
    applicants: "50",
    status: "Active",
  },
  {
    id: "5",
    name: "Chevening Scholarships",
    subTitle: "Undergraduate Degree • PG",
    type: "Merit-Based",
    provider: "UK Government",
    amount: "Full tuition + living expenses",
    deadline: "2024-11-15",
    applicants: "1,500",
    status: "Upcoming",
  },
  {
    id: "6",
    name: "DAAD Scholarships",
    subTitle: "Bachelor's or Master's Degree • UG/PG",
    type: "Merit-Based",
    provider: "German Government",
    amount: "Varies",
    deadline: "2024-08-15",
    applicants: "3,000",
    status: "Active",
  },
  {
    id: "7",
    name: "Erasmus Mundus Scholarships",
    subTitle: "Bachelor's Degree • PG",
    type: "Merit-Based",
    provider: "European Union",
    amount: "Varies",
    deadline: "2024-05-30",
    applicants: "1,000",
    status: "Closed",
  },
  {
    id: "8",
    name: "STEM Scholarship",
    subTitle: "Minimum 70% in 12th • UG",
    type: "Merit-Based",
    provider: "Various Institutions",
    amount: "₹75,000",
    deadline: "2024-09-10",
    applicants: "800",
    status: "Active",
  },
];


export const dummyJobData: JobData[] = [
  {
    id: "1",
    role: "Senior Software Engineer",
    company: "Tech Solutions Inc.",
    type: "Full Time",
    location: "Bangalore",
    postedDate: "2024-03-15",
    applicants: "145",
    status: "Active",
    salary: "₹50,000 - ₹1,00,000",
    experience: "Fresher's"
  },
  {
    id: "2",
    role: "Product Designer Intern",
    company: "Creative Studio",
    type: "Internship",
    location: "Mumbai",
    postedDate: "2024-03-20",
    applicants: "89",
    status: "Active",
    salary: "₹50,000 - ₹1,00,000",
    experience: "Fresher's"

  },
  {
    id: "3",
    role: "Marketing Manager",
    company: "Global Brands",
    type: "Full Time",
    location: "Delhi",
    postedDate: "2024-03-10",
    applicants: "230",
    status: "Closed",
    salary: "₹50,000 - ₹1,00,000",
    experience: "Fresher's"
  },
  {
    id: "4",
    role: "Data Scientist",
    company: "Analytics Co.",
    type: "Full Time",
    location: "Hyderabad",
    postedDate: "2024-03-18",
    applicants: "67",
    status: "Draft",
    salary: "₹50,000 - ₹1,00,000",
    experience: "Fresher's"
  },
  {
    id: "5",
    role: "Frontend Developer",
    company: "WebWorks",
    type: "Contract",
    location: "Remote",
    postedDate: "2024-03-22",
    applicants: "112",
    status: "Active",
    salary: "₹50,000 - ₹1,00,000",
    experience: "Fresher's"
  },
  {
    id: "6",
    role: "HR Executive",
    company: "People First",
    type: "Full Time",
    location: "Pune",
    postedDate: "2024-03-05",
    applicants: "45",
    status: "Closed",
    salary: "₹50,000 - ₹1,00,000",
    experience: "Fresher's"
  },
  {
    id: "7",
    role: "Sales Associate",
    company: "Retail Giants",
    type: "Part Time",
    location: "Chennai",
    postedDate: "2024-03-25",
    applicants: "34",
    status: "Active",
    experience: "Fresher's"
  },
  {
    id: "8",
    role: "Content Writer",
    company: "Media House",
    type: "Freelance",
    location: "Remote",
    postedDate: "2024-03-12",
    applicants: "156",
    status: "Active",
    salary: "₹50,000 - ₹1,00,000",
    experience: "Fresher's"
  },
];